//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Client_MAIN.RoutingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoCoordinate", Namespace="http://schemas.datacontract.org/2004/07/System.Device.Location")]
    [System.SerializableAttribute()]
    public partial class GeoCoordinate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HorizontalAccuracyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double VerticalAccuracyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Course {
            get {
                return this.CourseField;
            }
            set {
                if ((this.CourseField.Equals(value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HorizontalAccuracy {
            get {
                return this.HorizontalAccuracyField;
            }
            set {
                if ((this.HorizontalAccuracyField.Equals(value) != true)) {
                    this.HorizontalAccuracyField = value;
                    this.RaisePropertyChanged("HorizontalAccuracy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VerticalAccuracy {
            get {
                return this.VerticalAccuracyField;
            }
            set {
                if ((this.VerticalAccuracyField.Equals(value) != true)) {
                    this.VerticalAccuracyField = value;
                    this.RaisePropertyChanged("VerticalAccuracy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Itinerary_OBJ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] bboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Metadata metadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Route[] routesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] bbox {
            get {
                return this.bboxField;
            }
            set {
                if ((object.ReferenceEquals(this.bboxField, value) != true)) {
                    this.bboxField = value;
                    this.RaisePropertyChanged("bbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                if ((object.ReferenceEquals(this.metadataField, value) != true)) {
                    this.metadataField = value;
                    this.RaisePropertyChanged("metadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Route[] routes {
            get {
                return this.routesField;
            }
            set {
                if ((object.ReferenceEquals(this.routesField, value) != true)) {
                    this.routesField = value;
                    this.RaisePropertyChanged("routes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Metadata", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Metadata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string attributionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Engine engineField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Query queryField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string serviceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private long timestampField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string attribution {
                get {
                    return this.attributionField;
                }
                set {
                    if ((object.ReferenceEquals(this.attributionField, value) != true)) {
                        this.attributionField = value;
                        this.RaisePropertyChanged("attribution");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Engine engine {
                get {
                    return this.engineField;
                }
                set {
                    if ((object.ReferenceEquals(this.engineField, value) != true)) {
                        this.engineField = value;
                        this.RaisePropertyChanged("engine");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Query query {
                get {
                    return this.queryField;
                }
                set {
                    if ((object.ReferenceEquals(this.queryField, value) != true)) {
                        this.queryField = value;
                        this.RaisePropertyChanged("query");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string service {
                get {
                    return this.serviceField;
                }
                set {
                    if ((object.ReferenceEquals(this.serviceField, value) != true)) {
                        this.serviceField = value;
                        this.RaisePropertyChanged("service");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public long timestamp {
                get {
                    return this.timestampField;
                }
                set {
                    if ((this.timestampField.Equals(value) != true)) {
                        this.timestampField = value;
                        this.RaisePropertyChanged("timestamp");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Route", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(double[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(double[][]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.GeoCoordinate))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Metadata))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Engine))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Query))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Route[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Segment[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Segment))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Step[]))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Step))]
        [System.Runtime.Serialization.KnownTypeAttribute(typeof(CS_Client_MAIN.RoutingService.Itinerary_OBJ.Summary))]
        public partial class Route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double[] bboxField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string geometryField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private object[] legsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Segment[] segmentsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Summary summaryField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int[] way_pointsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double[] bbox {
                get {
                    return this.bboxField;
                }
                set {
                    if ((object.ReferenceEquals(this.bboxField, value) != true)) {
                        this.bboxField = value;
                        this.RaisePropertyChanged("bbox");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string geometry {
                get {
                    return this.geometryField;
                }
                set {
                    if ((object.ReferenceEquals(this.geometryField, value) != true)) {
                        this.geometryField = value;
                        this.RaisePropertyChanged("geometry");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public object[] legs {
                get {
                    return this.legsField;
                }
                set {
                    if ((object.ReferenceEquals(this.legsField, value) != true)) {
                        this.legsField = value;
                        this.RaisePropertyChanged("legs");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Segment[] segments {
                get {
                    return this.segmentsField;
                }
                set {
                    if ((object.ReferenceEquals(this.segmentsField, value) != true)) {
                        this.segmentsField = value;
                        this.RaisePropertyChanged("segments");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Summary summary {
                get {
                    return this.summaryField;
                }
                set {
                    if ((object.ReferenceEquals(this.summaryField, value) != true)) {
                        this.summaryField = value;
                        this.RaisePropertyChanged("summary");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int[] way_points {
                get {
                    return this.way_pointsField;
                }
                set {
                    if ((object.ReferenceEquals(this.way_pointsField, value) != true)) {
                        this.way_pointsField = value;
                        this.RaisePropertyChanged("way_points");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Engine", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Engine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.DateTime build_dateField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.DateTime graph_dateField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string versionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.DateTime build_date {
                get {
                    return this.build_dateField;
                }
                set {
                    if ((this.build_dateField.Equals(value) != true)) {
                        this.build_dateField = value;
                        this.RaisePropertyChanged("build_date");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.DateTime graph_date {
                get {
                    return this.graph_dateField;
                }
                set {
                    if ((this.graph_dateField.Equals(value) != true)) {
                        this.graph_dateField = value;
                        this.RaisePropertyChanged("graph_date");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string version {
                get {
                    return this.versionField;
                }
                set {
                    if ((object.ReferenceEquals(this.versionField, value) != true)) {
                        this.versionField = value;
                        this.RaisePropertyChanged("version");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Query", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double[][] coordinatesField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string formatField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string profileField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double[][] coordinates {
                get {
                    return this.coordinatesField;
                }
                set {
                    if ((object.ReferenceEquals(this.coordinatesField, value) != true)) {
                        this.coordinatesField = value;
                        this.RaisePropertyChanged("coordinates");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string format {
                get {
                    return this.formatField;
                }
                set {
                    if ((object.ReferenceEquals(this.formatField, value) != true)) {
                        this.formatField = value;
                        this.RaisePropertyChanged("format");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string profile {
                get {
                    return this.profileField;
                }
                set {
                    if ((object.ReferenceEquals(this.profileField, value) != true)) {
                        this.profileField = value;
                        this.RaisePropertyChanged("profile");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Summary", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Summary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double distanceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double durationField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double distance {
                get {
                    return this.distanceField;
                }
                set {
                    if ((this.distanceField.Equals(value) != true)) {
                        this.distanceField = value;
                        this.RaisePropertyChanged("distance");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double duration {
                get {
                    return this.durationField;
                }
                set {
                    if ((this.durationField.Equals(value) != true)) {
                        this.durationField = value;
                        this.RaisePropertyChanged("duration");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Segment", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Segment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double distanceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double durationField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private CS_Client_MAIN.RoutingService.Itinerary_OBJ.Step[] stepsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double distance {
                get {
                    return this.distanceField;
                }
                set {
                    if ((this.distanceField.Equals(value) != true)) {
                        this.distanceField = value;
                        this.RaisePropertyChanged("distance");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double duration {
                get {
                    return this.durationField;
                }
                set {
                    if ((this.durationField.Equals(value) != true)) {
                        this.durationField = value;
                        this.RaisePropertyChanged("duration");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public CS_Client_MAIN.RoutingService.Itinerary_OBJ.Step[] steps {
                get {
                    return this.stepsField;
                }
                set {
                    if ((object.ReferenceEquals(this.stepsField, value) != true)) {
                        this.stepsField = value;
                        this.RaisePropertyChanged("steps");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Itinerary_OBJ.Step", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.SerializableAttribute()]
        public partial class Step : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double distanceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double durationField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string instructionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string nameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int typeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int[] way_pointsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double distance {
                get {
                    return this.distanceField;
                }
                set {
                    if ((this.distanceField.Equals(value) != true)) {
                        this.distanceField = value;
                        this.RaisePropertyChanged("distance");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double duration {
                get {
                    return this.durationField;
                }
                set {
                    if ((this.durationField.Equals(value) != true)) {
                        this.durationField = value;
                        this.RaisePropertyChanged("duration");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string instruction {
                get {
                    return this.instructionField;
                }
                set {
                    if ((object.ReferenceEquals(this.instructionField, value) != true)) {
                        this.instructionField = value;
                        this.RaisePropertyChanged("instruction");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string name {
                get {
                    return this.nameField;
                }
                set {
                    if ((object.ReferenceEquals(this.nameField, value) != true)) {
                        this.nameField = value;
                        this.RaisePropertyChanged("name");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int type {
                get {
                    return this.typeField;
                }
                set {
                    if ((this.typeField.Equals(value) != true)) {
                        this.typeField = value;
                        this.RaisePropertyChanged("type");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int[] way_points {
                get {
                    return this.way_pointsField;
                }
                set {
                    if ((object.ReferenceEquals(this.way_pointsField, value) != true)) {
                        this.way_pointsField = value;
                        this.RaisePropertyChanged("way_points");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingService.I_ItineraryService")]
    public interface I_ItineraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getCorrectAdress", ReplyAction="http://tempuri.org/I_ItineraryService/getCorrectAdressResponse")]
        string[] getCorrectAdress(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getCorrectAdress", ReplyAction="http://tempuri.org/I_ItineraryService/getCorrectAdressResponse")]
        System.Threading.Tasks.Task<string[]> getCorrectAdressAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getCoordonateWithUniqueCorrectAdress", ReplyAction="http://tempuri.org/I_ItineraryService/getCoordonateWithUniqueCorrectAdressRespons" +
            "e")]
        CS_Client_MAIN.RoutingService.GeoCoordinate getCoordonateWithUniqueCorrectAdress(string correctAdrress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getCoordonateWithUniqueCorrectAdress", ReplyAction="http://tempuri.org/I_ItineraryService/getCoordonateWithUniqueCorrectAdressRespons" +
            "e")]
        System.Threading.Tasks.Task<CS_Client_MAIN.RoutingService.GeoCoordinate> getCoordonateWithUniqueCorrectAdressAsync(string correctAdrress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getItinerary", ReplyAction="http://tempuri.org/I_ItineraryService/getItineraryResponse")]
        CS_Client_MAIN.RoutingService.Itinerary_OBJ getItinerary(string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getItinerary", ReplyAction="http://tempuri.org/I_ItineraryService/getItineraryResponse")]
        System.Threading.Tasks.Task<CS_Client_MAIN.RoutingService.Itinerary_OBJ> getItineraryAsync(string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/printTest", ReplyAction="http://tempuri.org/I_ItineraryService/printTestResponse")]
        void printTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/printTest", ReplyAction="http://tempuri.org/I_ItineraryService/printTestResponse")]
        System.Threading.Tasks.Task printTestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_ItineraryServiceChannel : CS_Client_MAIN.RoutingService.I_ItineraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_ItineraryServiceClient : System.ServiceModel.ClientBase<CS_Client_MAIN.RoutingService.I_ItineraryService>, CS_Client_MAIN.RoutingService.I_ItineraryService {
        
        public I_ItineraryServiceClient() {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ItineraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCorrectAdress(string input) {
            return base.Channel.getCorrectAdress(input);
        }
        
        public System.Threading.Tasks.Task<string[]> getCorrectAdressAsync(string input) {
            return base.Channel.getCorrectAdressAsync(input);
        }
        
        public CS_Client_MAIN.RoutingService.GeoCoordinate getCoordonateWithUniqueCorrectAdress(string correctAdrress) {
            return base.Channel.getCoordonateWithUniqueCorrectAdress(correctAdrress);
        }
        
        public System.Threading.Tasks.Task<CS_Client_MAIN.RoutingService.GeoCoordinate> getCoordonateWithUniqueCorrectAdressAsync(string correctAdrress) {
            return base.Channel.getCoordonateWithUniqueCorrectAdressAsync(correctAdrress);
        }
        
        public CS_Client_MAIN.RoutingService.Itinerary_OBJ getItinerary(string start, string end) {
            return base.Channel.getItinerary(start, end);
        }
        
        public System.Threading.Tasks.Task<CS_Client_MAIN.RoutingService.Itinerary_OBJ> getItineraryAsync(string start, string end) {
            return base.Channel.getItineraryAsync(start, end);
        }
        
        public void printTest() {
            base.Channel.printTest();
        }
        
        public System.Threading.Tasks.Task printTestAsync() {
            return base.Channel.printTestAsync();
        }
    }
}
