//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_CLIENT.ItinearyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItinearyService.I_ItineraryService")]
    public interface I_ItineraryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/toString", ReplyAction="http://tempuri.org/I_ItineraryService/toStringResponse")]
        string toString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/toString", ReplyAction="http://tempuri.org/I_ItineraryService/toStringResponse")]
        System.Threading.Tasks.Task<string> toStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getItinerary", ReplyAction="http://tempuri.org/I_ItineraryService/getItineraryResponse")]
        void getItinerary(string start, string arrival);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ItineraryService/getItinerary", ReplyAction="http://tempuri.org/I_ItineraryService/getItineraryResponse")]
        System.Threading.Tasks.Task getItineraryAsync(string start, string arrival);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_ItineraryServiceChannel : CS_CLIENT.ItinearyService.I_ItineraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_ItineraryServiceClient : System.ServiceModel.ClientBase<CS_CLIENT.ItinearyService.I_ItineraryService>, CS_CLIENT.ItinearyService.I_ItineraryService {
        
        public I_ItineraryServiceClient() {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ItineraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ItineraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string toString() {
            return base.Channel.toString();
        }
        
        public System.Threading.Tasks.Task<string> toStringAsync() {
            return base.Channel.toStringAsync();
        }
        
        public void getItinerary(string start, string arrival) {
            base.Channel.getItinerary(start, arrival);
        }
        
        public System.Threading.Tasks.Task getItineraryAsync(string start, string arrival) {
            return base.Channel.getItineraryAsync(start, arrival);
        }
    }
}
